# Generated by Django 6.0 on 2025-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_room_roombooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='date',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='temo-room', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='fee_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
